# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: apolloschurchapp
  UNIVERSAL_LINK_HOST: https://longhollow-web.vercel.app
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
  FLAG_LIMIT: 1
VIMEO:
  TOKEN: ${VIMEO_TOKEN}
DATABASE:
  URL: ${DATABASE_URL}
  OPTIONS:
    dialectOptions:
      ssl:
        require: false
        rejectUnauthorized: false
BUGSNAG:
  ## Optional, but you'll need to remove references to @apollosproject/bugsnag if you don't wish to use.
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
  IMAGE_URL: https://rock.longhollow.com/GetImage.ashx
  SHARE_URL: https://longhollow.herokuapp.com
  # This should match the timezone of the Rock server
  TIMEZONE: 'America/Chicago'
  USE_PLUGIN: true
  SHOW_INACTIVE_CONTENT: ${ROCK_SHOW_INACTIVE_CONTENT}
  VERSION: 11
UNIVERSAL_LINKS:
  # This should be your app's bundle ID, as found in your info.plist.
  APPLE_APP_ID: com.longhollow.churchapp
  # This should be your app's team ID, as found in Xcode
  APPLE_TEAM_ID: 6QZF6PFAQS
  # Where should a user be redirected if they don't have your app installed?
  APP_STORE_LINK: https://longhollow.com
  PLAY_STORE_LINK: https://longhollow.com
  # Your app Id, as found in your app/build.gradle.
  GOOGLE_APP_ID: com.longhollow
  # https://docs.getsocial.im/knowledge-base/android-signing-key-sha256/
  GOOGLE_KEYSTORE_SHA256: FA:30:F5:C2:8F:ED:D7:F8:C2:16:8C:6A:95:88:56:0A:68:40:A9:A7:FA:BE:42:05:45:05:2B:DD:C2:2C:B6:6A
ONE_SIGNAL:
  APP_ID: 74697261-f31d-489d-9a42-aaf6b2529de3
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: https://longhollow.online.church/
  WEB_VIEW_URL: https://longhollow.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
  SEARCH_INDEX: prod_ContentItem
  # Configure Algolia custom settings here
  # https://www.algolia.com/doc/api-reference/settings-api-parameters/
  CONFIGURATION:
    searchableAttributes:
      - title
      - unordered(summary)
    attributesForFaceting:
      - category
      - location
      - ministry
      - tripType
      - daysAvailable
      - serviceArea
      - opportunityType
      - relatedSkills
      - isGroupEvent
      - speaker
      - topics
      - bookOfTheBible
    #customRankings:
    # NOT CURRENTLY INCLUDED
    # This just demonstrates what's possible
    # To include likedCount (or any other field) override search package
    # and add field to config below
    #- desc(likedCount)
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
ANALYTICS:
  # Filling out these fields will automatically enable analytics tracking
  # on the accompanying service
  SEGMENT_KEY:
  GA_ID:
  USE_ROCK: false
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    CSB: 'a556c5305ee15c3f-01'
    WEB: '9879dbb7cfe39e4d-01'
    KJV: 'de4e12af7f28f599-02'
CLOUDINARY:
  # Cloudinary is used to improve image loading
  # value should look something like
  # cloudinary://123123123:adkfnla_adASDv_adAS@test
  URL: ${CLOUDINARY_URL}

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  INTERACTIONS:
    # Name of the InteractionChannel that will be created per EntityType
    CHANNEL_NAME: Apollos App
    # Prefix for the name of the InteractionComponent that will be created per Entity
    COMPONENT_NAME: Apollos App Component
    # 512 is "Mobile App"
    CHANNEL_MEDIUM_TYPE_ID: 512

  CONTENT_ITEM:
    ContentSeriesContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [9, 13]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [10]
    MediaContentItem:
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
    WeekendContentItem:
      ContentChannelId: [14]
      EntityType: ContentChannelItem
    ContentItem:
      EntityType: ContentChannelItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 425

  # Apollos will pull these content channels and expose them in the app on the discover screen.
  ALL_CONTENT_CHANNELS: []

  # Apollos will pull content items from these channels and expose them on the user feed
  # However, it will not expose the channel itself.
  # These channels are also pulled when indexing searchable content.
  FEED_CONTENT_CHANNEL_IDS:
    - 14 # sermons
    - 35 # events
    - 36 # articles
    - 43 # mission trips
    - 44 # service opportunies
    - 45 # volunteer positions

  CAMPAIGN_CHANNEL_IDS:
    - 1

  SERMON_CHANNEL_ID: 14

  MOBILE_DEVICE_TYPE_ID: 671
TABS:
  HOME:
    - algorithms:
      - type: CONTENT_CHANNEL
        arguments:
          contentChannelId: 14
          limit: 1
      type: VerticalCardList
    - algorithms: [PERSONA_FEED]
      type: ActionList
      title: For you
      subtitle: Recommended
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 14
              - 35
              - 36
      type: VerticalCardList


  READ:
    - algorithms:
        - type: CONTENT_CHANNEL
          arguments:
            contentChannelId: 9
      type: VerticalCardList

  WATCH:
    - algorithms:
        - type: LATEST_SERIES_CHILDREN
          arguments:
            channelId: 13
      type: HeroList
      title: Catch up
      subtitle: The Weekend
    - algorithms:
        - type: CONTENT_CHANNEL
          arguments:
            contentChannelId: 13
      type: VerticalCardList
      subtitle: All series

  PRAY:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - type: VerticalPrayerList
      title: Your Prayers
